-- MySQL Script generated by MySQL Workbench
-- 11/12/15 16:00:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vendor` (
  `VendorID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `IdentType` ENUM('Cédula', 'Pasaporte', 'Cédula Extranjeria', 'Tarjeta Identidad') NOT NULL DEFAULT 'Cedula',
  `Ident` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `RegisterDate` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `City` ENUM('Cali', 'Palmira', 'Jamundi', 'Yumbo') NOT NULL,
  `Phone1` VARCHAR(45) NULL,
  `Phone2` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  `Twitter` VARCHAR(45) NULL,
  `Skype` VARCHAR(45) NULL,
  PRIMARY KEY (`VendorID`),
  UNIQUE INDEX `Ident_UNIQUE` (`Ident` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Client` (
  `ClientID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `IdentType` ENUM('Cédula', 'Pasaporte', 'Cédula Extranjeria', 'Tarjeta Identidad') NOT NULL DEFAULT 'Cedula',
  `Ident` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `City` ENUM('Cali', 'Palmira', 'Jamundi', 'Yumbo') NOT NULL,
  `Phone1` VARCHAR(45) NULL,
  `Phone2` VARCHAR(45) NULL,
  `Phone3` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  `Twitter` VARCHAR(45) NULL,
  `Skype` VARCHAR(45) NULL,
  `WebPage` VARCHAR(45) NULL,
  `Company` VARCHAR(45) NULL,
  PRIMARY KEY (`ClientID`),
  UNIQUE INDEX `Ident_UNIQUE` (`Ident` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProductCatalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProductCatalog` (
  `ProductCatalogID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  `Status` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`ProductCatalogID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `ProductCatalogID` INT NOT NULL,
  `Contract` VARCHAR(45) NOT NULL,
  `ClientID` INT NOT NULL,
  `VendorID` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fkClient_idx` (`ClientID` ASC),
  INDEX `fkProduct_idx` (`ProductCatalogID` ASC),
  INDEX `fkVendor_idx` (`VendorID` ASC),
  CONSTRAINT `fkClient`
    FOREIGN KEY (`ClientID`)
    REFERENCES `Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkProductCatalog`
    FOREIGN KEY (`ProductCatalogID`)
    REFERENCES `ProductCatalog` (`ProductCatalogID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkVendor`
    FOREIGN KEY (`VendorID`)
    REFERENCES `Vendor` (`VendorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beneficiary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beneficiary` (
  `BeneficiaryID` INT NOT NULL AUTO_INCREMENT,
  `ProductID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `IdentType` ENUM('Cédula', 'Pasaporte', 'Cédula Extranjeria', 'Tarjeta Identidad') NOT NULL DEFAULT 'Cedula',
  `Ident` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NULL,
  `Address` VARCHAR(45) NOT NULL,
  `City` ENUM('Cali', 'Palmira', 'Jamundi', 'Yumbo') NOT NULL,
  `Phone1` VARCHAR(45) NULL,
  `Phone2` VARCHAR(45) NULL,
  `Phone3` VARCHAR(45) NULL,
  `Mail` VARCHAR(45) NULL,
  `Facebook` VARCHAR(45) NULL,
  `Twitter` VARCHAR(45) NULL,
  `Skype` VARCHAR(45) NULL,
  `WebPage` VARCHAR(45) NULL,
  `Company` VARCHAR(45) NULL,
  PRIMARY KEY (`BeneficiaryID`),
  UNIQUE INDEX `Ident_UNIQUE` (`Ident` ASC),
  INDEX `fkProductByClient_idx` (`ProductID` ASC),
  CONSTRAINT `fkProductByClient`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Charge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Charge` (
  `ChargeID` INT NOT NULL AUTO_INCREMENT,
  `ProductID` INT NOT NULL,
  `Reference` VARCHAR(45) NULL,
  `ChargeDate` DATETIME NOT NULL,
  `ChargeType` ENUM('Debito', ' Credito') NOT NULL,
  `Value` DOUBLE NOT NULL,
  `Method` ENUM('Efectivo', 'Transferencia', 'Tarjeta Credito', ' Tarjeta Debito', 'Online', 'Cheque', 'Cupon') NOT NULL DEFAULT 'Efectivo',
  `Entity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ChargeID`),
  INDEX `fkProductID_idx` (`ProductID` ASC),
  CONSTRAINT `fkProductID`
    FOREIGN KEY (`ProductID`)
    REFERENCES `Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
